source 'http://rubygems.org'
ruby '2.2.2'

gem 'rails'
gem 'unicorn'
gem 'pg'
gem 'devise'
gem 'configatron'
gem 'kaminari'
gem 'paper_trail', '~> 4.0.0.beta'
gem 'friendly_id'
gem 'rails_autolink'
gem 'validate_url'
gem 'acts_as_list'

# assets
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'sass'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'compass-rails'
gem 'font-awesome-rails'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'google-analytics-turbolinks'
gem 'rails3-jquery-autocomplete'

# misc
gem 'rails_12factor'
gem 'newrelic_rpm'
gem 'rollbar'

group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'faker'
  # gem 'rack-mini-profiler'
  gem 'spring'
end
