source 'http://rubygems.org'
ruby '2.6.5'

gem 'rails'
gem 'unicorn'
gem 'pg'
gem 'slim'
gem 'devise'
gem 'configatron'
gem 'kaminari'
gem 'paper_trail'
gem 'friendly_id'
gem 'rails_autolink'
gem 'validate_url'
gem 'acts_as_list'

# assets
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'sass'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'font-awesome-rails'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'google-analytics-turbolinks'
gem 'rails3-jquery-autocomplete'

# misc
# gem 'rails_12factor'
gem 'newrelic_rpm'
gem 'rollbar'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  # gem 'pry-stack_explorer'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'faker'
  gem 'spring'
end
