development:
  adapter: postgresql
  encoding: unicode
  database: morio_development
  host: localhost
  pool: 5
  username: okumuramorio
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: morio_test
  host: localhost
  pool: 5
  username: okumuramorio
  password: password1

